name: build-5m-dataset

on:
  workflow_dispatch:
    inputs:
      top:
        description: Top N symbols
        required: true
        default: "400"
      start:
        description: Start date (YYYY-MM-DD)
        required: true
        default: "2024-01-01"
      end:
        description: End date (YYYY-MM-DD)
        required: true
        default: "2024-12-31"

concurrency: { group: build-5m-dataset, cancel-in-progress: true }

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POLYGON_KEY: ${{ secrets.POLYGON_KEY }}   # <-- make sure your secret is named exactly this
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyarrow

      # NEW: sanity check the secret is actually available to the job
      - name: Check POLYGON_KEY wiring
        run: |
          if [ -z "${POLYGON_KEY:-}" ]; then
            echo "ERROR: POLYGON_KEY is empty. Add it in Settings → Secrets and variables → Actions." >&2
            exit 1
          fi
          python - <<'PY'
import os
k = os.getenv("POLYGON_KEY","")
print("POLYGON_KEY length:", len(k))   # value stays masked in logs
PY

      - name: Build universe (top by median $ volume)
        run: |
          [ -n "${POLYGON_KEY:-}" ] || { echo "POLYGON_KEY missing"; exit 1; }
          python universe_top_adv_polygon.py \
            --top "${{ inputs.top }}" \
            --out universe_top${{ inputs.top }}.csv \
            --api-key "${POLYGON_KEY}"

      - name: Download 5m dataset (RTH)
        run: |
          [ -n "${POLYGON_KEY:-}" ] || { echo "POLYGON_KEY missing"; exit 1; }
          python etl_polygon_5m_ci.py \
            --symbols-file universe_top${{ inputs.top }}.csv \
            --start "${{ inputs.start }}" \
            --end   "${{ inputs.end }}" \
            --out-dir data_5m \
            --rth-only \
            --api-key "${POLYGON_KEY}"

      - name: Upload dataset artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-5m-${{ inputs.start }}-${{ inputs.end }}
          path: |
            universe_top${{ inputs.top }}.csv
            data_5m/
          retention-days: 14

