jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POLYGON_KEY: ${{ secrets.POLYGON_KEY || secrets.POLYGON_API_KEY || vars.POLYGON_KEY || vars.POLYGON_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyarrow

      - name: Verify POLYGON_KEY is available
        run: |
          if [ -z "$POLYGON_KEY" ]; then
            echo "ERROR: POLYGON_KEY/ POLYGON_API_KEY is empty. Add it in Settings → Secrets."
            exit 1
          fi
          echo "POLYGON_KEY length: ${#POLYGON_KEY}"

      - name: Build 5m dataset
        run: |
          set -e
          RTH_FLAG=""
          if [ "${{ inputs.rth }}" = "true" ]; then RTH_FLAG="--rth-only"; fi
          python build_5m_dataset.py \
            --top "${{ inputs.top }}" \
            --start "${{ inputs.start }}" \
            --end   "${{ inputs.end }}" \
            --out-dir data_5m \
            --universe-out "universe_top${{ inputs.top }}.csv" \
            $RTH_FLAG \
            --api-key "$POLYGON_KEY"
